name: MarketingFeeds-PROD-$(BuildID)

trigger: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: ado-pipeline-template-npm.yml

  - template: ado-pipeline-template-qa.yml

  - template: ado-pipeline-template-certs-prod.yml

  - template: ado-pipeline-template-build.yml
